name: Ejecucion Test del Proyecto

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      cucumber_tag:
        description: 'Tag de Cucumber a ejecutar'
        required: true
        default: '@CalendarFeature'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean test -Dcucumber.filter.tags="${{ inputs.cucumber_tag }}"

      # Generar reporte Serenity
      - name: Generate Serenity Report
        if: success() || failure()
        run: ./gradlew aggregate

      # Detectar dónde se generó el reporte
      - name: Prepare report folder
        if: success() || failure()
        run: |
          if [ -d "build/reports/serenity" ]; then
            echo "Report found in build/"
            mkdir -p public
            cp -r build/reports/serenity/* public/
          elif [ -d "target/site/serenity" ]; then
            echo "Report found in target/"
            mkdir -p public
            cp -r target/site/serenity/* public/
          else
            echo "Serenity report folder not found!"
            exit 1
          fi

      # Subir artefacto interno
      - name: Upload Serenity Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: Serenity Report
          path: public/

      # Configurar GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
